@startuml activity_Generuoti_pasiūlymus
skinparam style strictuml
skinparam swimlane {
  BorderColor #555
}
skinparam activity {
  BackgroundColor #FFFDE7
  BorderColor #F9A825
  DiamondBackgroundColor #E3F2FD
  DiamondBorderColor #1565C0
}

|Naudotojo posistemė|
start
if () then ([vartotojas neprisijunges])
  :Gauti visus pasiulymus iš duomenų bazės;
  fork
    :Rikiuoti maršrutus pagal populiarumo skaičių;
    :Rodyti pirmus 10 pasiulymus, pasiulymu lange;
    stop
  fork again
    :Gauti max populiarumo skaiciu;
    if () then ([Jei dar yra pasiulymu])
      if () then ([populiarumas == maxpopuliarumui])
        :Prie bendro ivertinimo prideti 0.2*100;
      else ([else])
        :Prie bendro ivertinimo prideti  0.2*(populiarumas/maxpopuliarumas * 100);
      endif
      :Tikrinti pasiulymo ratinga;
      if () then ([rating average >= 4])
        :Prie bendro ivertinimo prideti  0.2 * 100;
      else ([else])
        :Prie bendro ivertinimo prideti  0.2 * 50;
      endif
      :Tikrinti ar pasiulimas yra naujas;
      if () then ([pasiulimas naujas])
        :Prie bendro ivertinimo prideti 0.2*100;
      else ([else])
      endif
      :Tikrinti transporto parinktis;
      if () then ([parinktyse yra pazymeta masina])
        :max kelias = 15000(m);
      else ([else])
        :max kelias = 2000(m);
      endif
      :Tikrinti pasiulymo pirmo tasko atstuma nuo keliautojo;
      if () then ([kelias <= maxkelias])
        :Prie bendro ivertinimo prideti 0.2 *(100-(kelias / max kelias *100));
      else ([else])
      endif
      :Tikrinti ar keliautojas turi pridetu kelioniu;
      if () then ([neturi])
      else ([else])
        :Eiti per keliones;
        if () then ([nebera kelioniu])
        else ([else])
          :Prie sumos prideti keliones lankytinu vietu kiekis;
          if () then ([kelioniu kiekis ==5])
          else ([else])
          endif
        endif
        :Vidutinis vietu kiekis = suma/kiekis;
        if () then ([RoundUp( vidutinis vietu kiekis) == pasiulymo vietu kiekis])
          :Prie bendro ivertinimo prideti += 0.2*100;
        else ([else])
          :Prie bendro ivertinimo prideti +=0.2 * 60;
        endif
      endif
    else ([else])
      :Isrikiuoti pagal bendra ivertinima;
    endif
  end fork
else ([else])
  :Tikrinti miestą;
endif

@enduml