@startuml Architecture_Overview
skinparam style strictuml
skinparam packageStyle rectangle
left to right direction
title Architecture Overview

package "Frontend" as Frontend {
  package "Main" as FrontendMain {
    package "View" as FrontendView
    package "Controls" as FrontendControls
  }
}

package "Backend" as Backend {
  package "Controls" as BackendControls {
    package "Admin" as BackendAdmin
    package "Main" as BackendMain
  }

  package "Models" as Models {
    rectangle "Admin" as ModelAdmin
    rectangle "Deal" as ModelDeal
    rectangle "Dish" as ModelDish
    rectangle "FoodPlan" as ModelFoodPlan
    rectangle "Group" as ModelGroup
    rectangle "Menu" as ModelMenu
    rectangle "Preferences" as ModelPreferences
    rectangle "Route" as ModelRoute
    rectangle "RouteAttraction" as ModelRouteAttraction
    rectangle "RouteFoodPlace" as ModelRouteFoodPlace
    rectangle "RoutePlace" as ModelRoutePlace
    rectangle "Traveler" as ModelTraveler
    rectangle "Trip" as ModelTrip
    rectangle "User" as ModelUser
    rectangle "VisitedPlace" as ModelVisitedPlace
    rectangle "Dieta" as ModelDieta
  }
}

FrontendView ..> FrontendControls
Frontend ..> BackendControls
@enduml
