@startuml activity_Atsijungti
skinparam style strictuml
skinparam swimlane {
  BorderColor #555
}
skinparam activity {
  BackgroundColor #FFFDE7
  BorderColor #F9A825
  DiamondBackgroundColor #E3F2FD
  DiamondBorderColor #1565C0
}

|Naudotojas|
start
:Paspausti atsijungti mygtuką;
|Naudotojo posistemė|
:Tikrinti ar sesija aktyvi;
if () then ([Sesija aktyvi])
  :Rodyti patvirtinimą apie atsijungimą;
|Naudotojas|
  :Patvirtinti atisijungimo veiksmą;
|Naudotojo posistemė|
  :Ištrinti sesijos duomenis;
else ([else])
endif
:Nukreipti į prisijungimo puslapį;
stop

@enduml