@startuml activity_Kurti_kelione
skinparam style strictuml
skinparam swimlane {
  BorderColor #555
}
skinparam activity {
  BackgroundColor #FFFDE7
  BorderColor #F9A825
  DiamondBackgroundColor #E3F2FD
  DiamondBorderColor #1565C0
}

|Keliautojas|
start
:Pasirinkti „Kurti kelionę"
mygtuką;
|Naudotojo posistemė|
if () then ([Keliautojas nematęs tutorial lango])
  :Rodyti tutorial langą;
else ([else])
endif
:Rodyti pridėti draugą kaip keliautoją langą;
|Keliautojas|
:Pasirinkti ar keliautu su draugu;
if () then ([pasirinko prideti drauga])
|Naudotojo posistemė|
  :Tikrinti ar yra issaugotu indvidualiu parinkciu;
  if () then ([yra])
  else ([else])
    :Pateikti ar nori sujunti pasirinktis;
|Keliautojas|
    :Pasirinkti  sujungti pasirinktis;
    if () then ([sujungti])
|Naudotojo posistemė|
    else ([else])
    endif
|Keliautojas|
    if () then ([Nori sudaryti savo lankymo objektus])
|Naudotojo posistemė|
    else ([else])
|Keliautojas|
      :Pasirinkti sugeneruoti lankytinas vietas;
|Naudotojo posistemė|
      :Surinkti visų keliautojų
preferencijas iš profilių;
      if () then ([1 keliautojas])
        :Naudoti vieno keliautojo
preferencijų profilį;
      else ([else])
        :Sudėti kategorinius kintamuosius į vieną masyvą;
        :Apskaičiuoti vidurkį integer tipo kintamųjų;
        :Suformuoti bendrą
preferencijų profilį;
      endif
      :Gauti lankytinų vietų
sąrašą;
      :Apskaičiuoti kategorinių kintamųjų sutapimą. match(P, P_place);
      :Apskaičiuoti integer tipo kintamųjų skirtumą;
      :Normalizuoti individuolius preferences 0-100;
      :Išvesti bendrą heuristinį kintamąjį. 

sum(norm_p_match)/count;
      :Reitinguoti vietas
pagal balą B
(mažėjimo tvarka);
      :Parinkti N geriausių
vietų (N = keliautojo
pasirinktas skaičius);
    endif
    :Tikrinti ar telpa į laiką sum(*activity_time);
    if () then ([parodytas maisto plano generavimo pasiūlymas ir planas telpa į laiką])
    else ([else])
      if () then ([jei netelpa])
        :Rodyti siūlyti mažinti vietų skaičių langą;
|Keliautojas|
        :Pasirinkti mažesnį kelionių skaičių;
      else ([else])
|Naudotojo posistemė|
        :Rodyti siūlyti generuoti maisto planą;
|Keliautojas|
      endif
    endif
|Naudotojo posistemė|
    :Rodyti sėkmingai sugeneruotos kelionės plana apžiūrą;
    stop
  endif
else ([else])
endif

@enduml