@startuml activity_Peržiūrėti_meniu
skinparam style strictuml
skinparam swimlane {
  BorderColor #555
}
skinparam activity {
  BackgroundColor #FFFDE7
  BorderColor #F9A825
  DiamondBackgroundColor #E3F2FD
  DiamondBorderColor #1565C0
}

|Admin|
start
:Pasirinnkti meniu peržiūrą;
|Administratoriaus posistemė|
:Pateikti meniu peržiūros langą;
|Admin|
if () then ([nori ištrinti])
else ([else])
endif
stop

@enduml