@startuml activity_Redaguoti_profilį__preferences
skinparam style strictuml
skinparam swimlane {
  BorderColor #555
}
skinparam activity {
  BackgroundColor #FFFDE7
  BorderColor #F9A825
  DiamondBackgroundColor #E3F2FD
  DiamondBorderColor #1565C0
}

|Keliautojas|
start
:Pasirinkti redaguoti profilį;
|Naudotojo posistemė|
:Pateikti profilio redagavimo pasirinktis;
|Keliautojas|
:Redaguoti profilį;
|Naudotojo posistemė|
:Validuoti duomenis;
if () then ([Duomenys netinkami])
else ([else])
endif
:Redaguoti duomenų bazę;
:Rodyti patvirtinima
apie sékmingą redagavimą;
stop

@enduml