@startuml
skinparam style strictuml

title Ištrinti maisto vietą

actor "User" as user
boundary "AdminDashboardView" as ui
control "FoodController" as foodController
entity "FoodPlan" as foodPlan

user -> ui: Request Ištrinti maisto vietą
ui -> foodController: Forward request
foodController -> foodPlan: Execute business operation
foodPlan --> foodController: Return operation result
foodController --> ui: Build response
ui --> user: Present response
@enduml
