@startuml
skinparam style strictuml

title Pasirinkti specifines keliones parinktis

actor "User" as user
boundary "TravelerTripsView" as ui
control "TripsController" as tripsController
entity "Trip" as trip

user -> ui: Request Pasirinkti specifines keliones parinktis
ui -> tripsController: Forward request
tripsController -> trip: Execute business operation
trip --> tripsController: Return operation result
tripsController --> ui: Build response
ui --> user: Present response
@enduml
