@startuml
skinparam style strictuml

title Peržiūrėti kelią žemėlapy

actor "User" as user
boundary "TravelerTripsView" as ui
control "PlacesController" as placesController
entity "RouteAttraction" as routeAttraction

user -> ui: Request Peržiūrėti kelią žemėlapy
ui -> placesController: Forward request
placesController -> routeAttraction: Execute business operation
routeAttraction --> placesController: Return operation result
placesController --> ui: Build response
ui --> user: Present response
@enduml
