@startuml
skinparam style strictuml

title Prisijungti

actor "User" as user
boundary "GuestDealsView" as ui
control "AuthController" as authController
entity "User" as authUser

user -> ui: Request Prisijungti
ui -> authController: Forward request
authController -> authUser: Execute business operation
authUser --> authController: Return operation result
authController --> ui: Build response
ui --> user: Present response
@enduml
