@startuml
skinparam style strictuml

title Redaguoti maisto plana

actor "User" as user
boundary "TravelerTripsView" as ui
control "FoodController" as foodController
entity "FoodPlan" as foodPlan

user -> ui: Request Redaguoti maisto plana
ui -> foodController: Forward request
foodController -> foodPlan: Execute business operation
foodPlan --> foodController: Return operation result
foodController --> ui: Build response
ui --> user: Present response
@enduml
