@startuml
skinparam style strictuml

title Rekomenduoti pasiūlymus

actor "User" as user
boundary "GuestDealsView" as ui
control "DealsController" as dealsController
entity "Deal" as deal

user -> ui: Request Rekomenduoti pasiūlymus
ui -> dealsController: Forward request
dealsController -> deal: Execute business operation
deal --> dealsController: Return operation result
dealsController --> ui: Build response
ui --> user: Present response
@enduml
