@startuml Istrinti_maisto_vieta
skinparam style strictuml

actor Admin as A
boundary MainView as V
control JourneyController as FEC
control FoodController as BEC
entity RouteFoodPlace as E

ref over A, V, FEC, BEC : Perziureti_maisto_vietas

A -> V : selectFoodPlace(placeId)
A -> V : confirmDelete()
V -> FEC : deleteFoodPlace(placeId)
FEC -> BEC : deleteFoodPlace(placeId)
BEC -> E : findById(placeId)
BEC -> E : delete(placeId)
E --> BEC : ok
BEC --> FEC : ok
FEC --> V : placeDeleted()
V --> A : showSuccess("Maisto vieta ištrinta")
@enduml
