@startuml Istrinti_patiekala
skinparam style strictuml

actor Admin as A
boundary MainView as V
control JourneyController as FEC
control FoodController as BEC
entity Dish as E

ref over A, V, FEC, BEC : Perziureti_patiekalus

A -> V : selectDish(dishId)
A -> V : confirmDelete()
V -> FEC : deleteDish(dishId)
FEC -> BEC : deleteDish(dishId)
BEC -> E : findById(dishId)
E --> BEC : dish : Dish
BEC -> E : delete(dishId)
E --> BEC : ok
BEC --> FEC : ok
FEC --> V : dishDeleted()
V --> A : showSuccess("Patiekalas ištrintas")
@enduml
