@startuml Perziureti_meniu
skinparam style strictuml

actor Admin as A
boundary MainView as V
control JourneyController as FEC
control FoodController as BEC
entity Menu as E

A -> V : openMenuManagement()
V -> FEC : loadMenus()
FEC -> BEC : findAllMenus()
BEC -> E : findAll()
E --> BEC : menus : Menu[]
BEC --> FEC : menus : Menu[]
FEC --> V : render(menus)
V --> A : showMenuList(menus)
@enduml
