@startuml Perziureti_patiekalus
skinparam style strictuml

actor Admin as A
boundary MainView as V
control JourneyController as FEC
control FoodController as BEC
entity Dish as E

A -> V : openDishManagement()
V -> FEC : loadDishes()
FEC -> BEC : findAllDishes()
BEC -> E : findAll()
E --> BEC : dishes : Dish[]
BEC --> FEC : dishes : Dish[]
FEC --> V : render(dishes)
V --> A : showDishList(dishes)
@enduml
