@startuml Perziureti_visas_keliones
skinparam style strictuml

actor Admin as A
boundary TripListView as V
control TripListController as FEC
control AdminController as BEC
entity Trip as E

A -> V : openAllTripsView()
V -> FEC : loadAllTrips()
FEC -> BEC : findAllTrips()
BEC -> E : findAll()
E --> BEC : trips : Trip[]
BEC --> FEC : trips : Trip[]
FEC --> V : render(trips)
V --> A : showAllTrips(trips)
@enduml
