@startuml Perziureti_lankytinas_vietas
skinparam style strictuml

actor Admin as A
boundary MainView as V
control RouteController as FEC
control PlaceController as BEC
entity RoutePlace as E

A -> V : openPlacesManagement()
V -> FEC : loadPlaces()
FEC -> BEC : findAll()
BEC -> E : findAll()
E --> BEC : places : RoutePlace[]
BEC --> FEC : places : RoutePlace[]
FEC --> V : render(places)
V --> A : showPlacesList(places)
@enduml
