@startuml Perziureti_maisto_vietas
skinparam style strictuml

actor Admin as A
boundary MainView as V
control JourneyController as FEC
control FoodController as BEC
entity RouteFoodPlace as E

A -> V : openFoodPlacesManagement()
V -> FEC : loadFoodPlaces()
FEC -> BEC : findAllFoodPlaces()
BEC -> E : findAll()
E --> BEC : places : RouteFoodPlace[]
BEC --> FEC : places : RouteFoodPlace[]
FEC --> V : render(places)
V --> A : showFoodPlacesList(places)
@enduml
