@startuml Perziureti_pasiulymus_admin
skinparam style strictuml

actor Admin as A
boundary DealsView as V
control DealController as FEC
control "DealController" as BEC
entity Deal as E

A -> V : openDealsManagement()
V -> FEC : loadAllDeals()
FEC -> BEC : findAll()
BEC -> E : findAll()
E --> BEC : deals : Deal[]
BEC --> FEC : deals : Deal[]
FEC --> V : render(deals)
V --> A : showDealsList(deals)
@enduml
