@startuml Prideti_meniu
skinparam style strictuml

actor Admin as A
boundary MainView as V
control JourneyController as FEC
control FoodController as BEC
entity Menu as E

ref over A, V, FEC, BEC : Perziureti_meniu

A -> V : openAddMenuForm(foodPlaceId)
A -> V : submitMenuForm(name, description, foodPlaceId)
V -> FEC : addMenu(name, description, foodPlaceId)
FEC -> BEC : createMenu(name, description, foodPlaceId)
BEC -> E : save(name, description, foodPlaceId)
E --> BEC : menu : Menu
BEC --> FEC : menu : Menu
FEC --> V : menuAdded(menu)
V --> A : showSuccess("Meniu pridėtas")
@enduml
