@startuml Prideti_maisto_vieta
skinparam style strictuml

actor Admin as A
boundary MainView as V
control JourneyController as FEC
control FoodController as BEC
entity RouteFoodPlace as E

ref over A, V, FEC, BEC : Perziureti_maisto_vietas

A -> V : openAddFoodPlaceForm()
A -> V : submitForm(name, address, city, cuisine)
V -> FEC : addFoodPlace(name, address, city, cuisine)
FEC -> BEC : createFoodPlace(name, address, city, cuisine)
BEC -> E : save(name, address, city, cuisine)
E --> BEC : place : RouteFoodPlace
BEC --> FEC : place : RouteFoodPlace
FEC --> V : placeAdded(place)
V --> A : showSuccess("Maisto vieta pridėta")
@enduml
