@startuml Prideti_lankytina_vieta
skinparam style strictuml

actor Admin as A
boundary MainView as V
control RouteController as FEC
control PlaceController as BEC
entity RoutePlace as E

ref over A, V, FEC, BEC : Perziureti_lankytinas_vietas

A -> V : openAddPlaceForm()
A -> V : submitPlaceForm(name, address, city, type, description)
V -> FEC : addPlace(name, address, city, type, description)
FEC -> BEC : createPlace(name, address, city, type, description)
BEC -> E : save(name, address, city, type, description)
E --> BEC : place : RoutePlace
BEC --> FEC : place : RoutePlace
FEC --> V : placeAdded(place)
V --> A : showSuccess("Lankytina vieta pridėta")
@enduml
