@startuml activity_Redaguoti_kelionę
skinparam style strictuml
skinparam swimlane {
  BorderColor #555
}
skinparam activity {
  BackgroundColor #FFFDE7
  BorderColor #F9A825
  DiamondBackgroundColor #E3F2FD
  DiamondBorderColor #1565C0
}

|Keliautojas|
start
|Sistema|
:Pateikti kelionés
redagavimo langa;
|Keliautojas|
if () then ([norint istrinti lankytina vieta])
|Sistema|
  :Tikrinti busena;
  if () then ([busena aktyvi])
    :Pateikti klaidos langa;
  else ([else])
    :Pateikti lankytinu vietu pasirinkima;
|Keliautojas|
    :Issirinkti lankytina vieta;
|Sistema|
    :Pateikti patvirtinima istrinti lankytina vieta ir pakeisti marsruta;
|Keliautojas|
    :Patvirtina istrinti kelione;
|Sistema|
    :Issimti lankytina vieta is kelioniu saraso;
    if () then ([lankytinu vietu kiekis daugiau uz 0])
    else ([else])
    endif
    :Panaikinti kelione is pridetu;
    stop
  endif
else ([else])
endif

@enduml