@startuml activity_Pasinaudoti_pasiūlymu
skinparam style strictuml
skinparam swimlane {
  BorderColor #555
}
skinparam activity {
  BackgroundColor #FFFDE7
  BorderColor #F9A825
  DiamondBackgroundColor #E3F2FD
  DiamondBorderColor #1565C0
}

|Keliautojas|
start
:pasirenka naudotis pasiulymu;
|Naudotojo posistemė|
:Rodyti issaugotus pasiulimus;
|Keliautojas|
:Pasirinkti pasiulyma;
|Naudotojo posistemė|
:Padidinti pasiulymo populiaruma vienu;
:Pateikti datos pasirinkima;
|Keliautojas|
:Pasirinkti keliones data;
|Naudotojo posistemė|
:keliones numeri padaryti pasiulimo numeriu;
:Prideti kelione;
stop

@enduml