@startuml activity_Kurti_kelione_su_draugu
skinparam style strictuml
skinparam swimlane {
  BorderColor #555
}
skinparam activity {
  BackgroundColor #FFFDE7
  BorderColor #F9A825
  DiamondBackgroundColor #E3F2FD
  DiamondBorderColor #1565C0
}

|Naudotojo posistemė|
start
:Tikrinti ar yra issaugotu indvidualiu parinkciu;
if () then ([yra])
  :Pateikti pasirinkimą keisti parinktis;
  if () then ([nori keisti])
  else ([else])
  endif
else ([else])
endif
stop

@enduml