@startuml activity_Redaguoti_maisto_plana
skinparam style strictuml
skinparam swimlane {
  BorderColor #555
}
skinparam activity {
  BackgroundColor #FFFDE7
  BorderColor #F9A825
  DiamondBackgroundColor #E3F2FD
  DiamondBorderColor #1565C0
}

|Naudotojo posistemė|
start
:Tikrinti ar kelione turi maisto plana;
if () then ([kelione neturi maisto plano])
  :Pateikti pasirinkima generuoti maisto plana;
|Keliautojas|
  if () then ([norint generuoti maisto plana])
|Naudotojo posistemė|
  else ([else])
  endif
|Keliautojas|
  stop
else ([else])
|Naudotojo posistemė|
  :Pateikti maisto redagavimo langa;
|Keliautojas|
  if () then ([noritn istrinti maisto plana])
|Naudotojo posistemė|
    :Panaikinti keliones maisto plana;
  else ([else])
    :Panaikinti esama maisto plana;
  endif
endif

@enduml