@startuml activity_Sudaryti_maršruta
skinparam style strictuml
skinparam swimlane {
  BorderColor #555
}
skinparam activity {
  BackgroundColor #FFFDE7
  BorderColor #F9A825
  DiamondBackgroundColor #E3F2FD
  DiamondBorderColor #1565C0
}

|Naudotojo posistemė|
start
:Gauti keliones lankytinas vietas;
if () then ([Lankytinų vietų >1])
  :Pasirinkti dar nenaudota lankytina vietą;
  :Įrašyti lankytiną vietą  kaip tašką grafe;
  if () then ([Dar yra neįrašytų lankytinų vietų])
  else ([else])
    :Pasirinkti dar nenaudota lankytinų vietų porą;
|Google maps|
    :Atrasti keliavimo laiką (sekundėmis) tarp parinktos lankytinų vietų poros;
|Naudotojo posistemė|
    :Įrašyti lanką su svoriais, lygu keliavimo laikui sekundėmis, tarp parinktos lankytinų vietų  taškų poros grafe;
    if () then ([Dar yra nenaudotų lankytinų vietų porų])
    else ([else])
      :Sukurti dvipusį linkedList, kurio kiekvienas elementas yra atskiras maršrutas su masyvais  'Pažymėti', 'Maršrutas ir kintamaji laikas;
      :Įdėti pirmosios lankytinos vietos sąraše tašką į pirmo elemento  'Pažymėti' ir 'Maršrutas' masyvus;
      :Parinkti pirmą elementą kaip aktyvųjį elementą;
      if () then ([Dar yra nepažymėtų ir nepanaudotų taškų])
        :Sukurti naują elementą į kurį rodys aktyvusis elementas;
        :Nukopijuoti 'Maršrutas' masyvą į sekantį elementą;
        :Pakeisti aktyvųjį elementą į sekantį;
        :Pridėti sekantį nepažymėta ir nepanaudota tašką į  'Maršrutas' masyvą aktyviame elemente;
        :Pridėti prie laikas kintamojo paskutinių dviejų taškų 'Maršutas' masyvę lanko svorį;
        :Patikrinti ar visi taškai aktyviame elemente yra masyve 'Maršrutas';
        if () then ([taip])
        else ([else])
          :Palyginti aktyvaus elemento laikas kintamajį su išsaugoto greičiausio maršruto laikas kintamuoju;
          if () then ([Aktyvusis elementas turi mažesnį laikas  kintamąjį už išsaugoto maršruto arba dar  nėra greičiausio maršuto])
            :Išsaugoti aktyvųjį elementą kaip greičiausią;
          else ([else])
          endif
          :Patikrinti ar pirmasis elementas turi visus taškus masyve 'Pažymėti';
          if () then ([Pirmas elementas turi visus taškus masyve 'Pažymėti'])
            :Grąžinti išsaugotą greičiausią elementą;
          else ([else])
          endif
          stop
        endif
      else ([else])
        :Grįžti į buvusį elementą;
        :Paskutinį sekančio elemento 'Maršrutas' tašką įdėti į aktyvaus elemento 'Pažymėti' masyvą;
        :Ištrinti sekantį elementą;
      endif
    endif
  endif
else ([else])
  :Išsaugoti maršrutą kaip tą vieną lankytiną vietą;
endif

@enduml